### PR TITLE
Added PDSO, Practical DevSecOps, CDP and CDE.

### PR DESCRIPTION
**Pull request by tsluyter**
As the name of the company suggests, PDSO offers trainings that focus on implementing security in DevOps, or DevSecOps. They teach you how to improve/secure your SDLC and how to implement automated security testing (like SAST, SCA, DAST and more) plus hardening (Ansible) and compliance through your CI/CD pipelines.

CDP is their entry-level "Professional" cert, while CDE is their "Expert" level cert.

### CODE REVIEW

**Comment by tsluyter** [comment]
Pinging @sinecurelife. You doing okay?

**Comment by sinecurelife** [comment]
Hey there! I'm alive. I keep my sanity on this project by gathering changes over a month or so then doing them all at once. I'm getting ready for the May push now.

**Comment by tsluyter** [comment]
> I keep my sanity on this project

Excellent! I'm happy to hear it, because I was actually worried the inverse might've happend. It'd suck if your wonderful project went down due to its own success.

Thanks for your hard work!

**Comment by sinecurelife** [comment]
Thanks for this updated information. Life happened but I'm finally doing an update.

**Pull request merged**
